### ISSUE TITLE
零售库存管理

### ISSUE THREAD

**Issue by richfox** [MicrosoftDocs/architecture-center.zh-cn#77]
如何实现云上的库存管理系统，有没有代码示例参考一下
howto realize a small inventory control system with azure, do u have a code sample?
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3d11b63e-15f8-5a33-5ab6-eeaf1f7db932
* Version Independent ID: 6c36fc2f-a896-53f1-34fa-934e6e216158
* Content: [使用 Azure MySQL 的零售和电子商务 - Azure Solution Ideas](https://docs.microsoft.com/zh-cn/azure/architecture/solution-ideas/articles/retail-and-ecommerce-using-azure-database-for-mysql#feedback)
* Content Source: [docs/solution-ideas/articles/retail-and-ecommerce-using-azure-database-for-mysql.md](https://github.com/microsoftdocs/architecture-center.zh-cn/blob/live/docs/solution-ideas/articles/retail-and-ecommerce-using-azure-database-for-mysql.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by srvbpigh** [comment]
Hello, @richfox
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @richfox, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/architecture-center/issues/1919. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
